services:
  app:
    container_name: currency_app
    build: ./app
    depends_on:
      - db
    restart: on-failure


  db:
    container_name: currency_db
    image: mysql:8
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db-daily-currency-rate
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init/db-daily-currency-rate.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:


